version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass Letmein!